# Generated by Django 4.2.6 on 2023-10-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'Player', 'verbose_name_plural': 'Players'},
        ),
        migrations.AddField(
            model_name='player',
            name='foot',
            field=models.CharField(choices=[('both-footed', 'both-footed'), ('left', 'left'), ('right', 'right')], default='both-footed', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('LB', 'Left back'), ('RB', 'Right back'), ('CB', 'Center back'), ('GK', 'Goalkeeper'), ('DM', 'Defensive midfielder'), ('CM', 'Central midfielder'), ('LW', 'Left wing'), ('RW', 'Right wing'), ('STR', 'Striker')], default='LB', max_length=4),
            preserve_default=False,
        ),
    ]
